import time

if __name__ == "__main__":
    """
    how many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
    """
    start_time = time.time()
    terms = set()

    for a in range(2, 101):
        for b in range(2, 101):
            terms.add(a ** b)

    print(len(terms), time.time() - start_time)
